.github/workflows/kuttl-e2e-test.yaml
Update kuttl version which contains commit https://github.com/kudobuilder/kuttl/commit/25776a2afa508ca307079161900cdd5a07d7fb39
=> Bump kuttl to v0.11.1

Makefile, api/v1/kubectlstorageosconfig_types.go, cmd/plugin/cli/bundle.go, cmd/plugin/cli/install.go, cmd/plugin/cli/uninstall.go, cmd/plugin/cli/upgrade.go, pkg/installer/endpoints.go, pkg/installer/installer.go, pkg/installer/upgrade.go, pkg/installer/utils.go, pkg/utils/k8s.go, pkg/version/version.go
This change replaces URL based operator manifests download to job execution with versioned manifests image.
=> Use manifests images for operator

Makefile, cmd/plugin/cli/upgrade.go, pkg/installer/endpoints.go, pkg/installer/etcdctl.go, pkg/installer/etcdctl_test.go, pkg/installer/upgrade.go, tests/e2e/installer/08-cluster-secret-old.yaml, tests/e2e/installer/09-upgrade.yaml
Also updated some unit tests (make target was not testing them before)
=> Detect ETCD endpoints for upgrade

cmd/plugin/cli/bundle.go, cmd/plugin/cli/preflight.go, cmd/plugin/cli/root.go, go.mod, go.sum, pkg/preflight/interactive_results.go, pkg/preflight/run.go, pkg/preflight/stdout_results.go, pkg/preflight/upload_results.go, pkg/troubleshoot/run.go, preflight/preflight-kernel.yaml, preflight/preflight.yaml, preflight/support.yaml
Adds the preflight command using the fork at https://github.com/croomes/troubleshoot/tree/remote-host-collector
Run as: `bin/kubectl-storageos preflight preflight/preflight.yaml --collector-image croomes/troubleshoot:latest`
=> Add preflight command

api/v1/kubectlstorageosconfig_types.go, cmd/plugin/cli/install.go, cmd/plugin/cli/uninstall.go, cmd/plugin/cli/upgrade.go, pkg/installer/install.go, pkg/installer/installer.go, pkg/installer/uninstall.go, pkg/installer/utils.go, tests/e2e/installer/00-install-full.yaml, tests/e2e/installer/01-uninstall.yaml, tests/e2e/installer/03-install-skip-etcd.yaml, tests/e2e/installer/04-uninstall.yaml, tests/e2e/installer/10-uninstall.yaml, tests/e2e/installer/kubectl-storageos-config.yaml
Change `--skip-etcd` flag to `--include-etcd`
Note: not ready to merge, will rebase once #22 is merged
=> Change default behavior of ETCD installation

api/v1/kubectlstorageosconfig_types.go, cmd/plugin/cli/install.go, cmd/plugin/cli/upgrade.go, config/crd/bases/storageos.com_kubectlstorageosconfigs.yaml, pkg/installer/install.go, pkg/installer/installer.go, pkg/installer/uninstall.go, pkg/installer/upgrade.go, pkg/utils/k8s.go
This new flag helps automation nerds to wait until cluster is ready.
=> New wait flag for install/upgrade

README.MD, cmd/plugin/cli/install.go, cmd/plugin/cli/preflight.go, cmd/plugin/cli/uninstall.go, config/samples/_v1_kubectlstorageosconfig.yaml
Add specific descriptions for commands under installer package
=> Update README with commands and additional info

cmd/plugin/cli/install.go, cmd/plugin/cli/uninstall.go, cmd/plugin/cli/upgrade.go, pkg/installer/endpoints.go, pkg/installer/install.go, pkg/installer/installer.go, pkg/installer/uninstall.go, pkg/installer/upgrade.go, pkg/installer/utils.go, pkg/utils/k8s.go, pkg/utils/yaml.go
There are a bunch of error checks throughout the code that can be shortened + some needless error checks.
PR also fixes a couple of comments/prints
=> Gardening - Single line err checks + some other tidy ups 

api/v1/kubectlstorageosconfig_types.go, cmd/plugin/cli/install.go, cmd/plugin/cli/uninstall.go, cmd/plugin/cli/upgrade.go, config/crd/bases/storageos.com_kubectlstorageosconfigs.yaml, main.go, pkg/installer/installer.go, pkg/installer/uninstall.go, pkg/installer/utils.go, pkg/utils/k8s.go, pkg/utils/utils.go, pkg/version/github.go
Initial commit of new way error handling to be able to display nice and meaningful errors to the user.
=> Userfriendly errors part 1

.github/workflows/linter.yml
Note that the `VALIDATE_ALL_CODEBASE: false` value means that this workflow will only run on code that is changed and therefore will not find issues with existing code.
I have run the test on exsiting code seperately and will create another PR addressing the issues found.
=> Add super-linter workflow

pkg/consts/consts.go, pkg/utils/yaml_test.go, tests/e2e/installer/00-assert.yaml, tests/e2e/installer/03-assert.yaml, tests/e2e/installer/05-assert.yaml, tests/e2e/installer/09-assert.yaml, tests/e2e/installer/11-assert.yaml, tests/e2e/installer/12-errors.yaml, tests/e2e/installer/14-assert.yaml
Updates to use the new object names introduced in https://github.com/storageos/operator/pull/14.
=> Operator object name changes

pkg/installer/install.go, pkg/utils/k8s.go
Checks that the operator's services are ready before proceeding to create the StorageOSCluster.
This should ensure that the validating webhook for the StorageOSCluster resource is ready before it's needed.
=> Wait for operator services to be ready

specs/support.yaml
Removes reliance on separate utils container and execs into node container instead.
=> Use utils in node container

cmd/plugin/cli/install.go, cmd/plugin/cli/uninstall.go, pkg/installer/install.go, pkg/installer/uninstall.go, pkg/installer/upgrade.go
Also include check to postpone namespace deletion until operator uninstall
=> Use installer's in memory config instead of passing params

pkg/installer/uninstall.go
Should fix intermittent e2e failures
=> Increase timeout and add NotFound check

cmd/plugin/cli/completion.go, cmd/plugin/cli/root.go
=> Completion script generator

specs/configmap-storageos-portal-manager.yaml, tests/e2e/installer/15-assert.yaml, tests/e2e/installer/17-assert.yaml, tests/e2e/installer/18-errors.yaml
Depends on:
https://github.com/storageos/portal-manager/pull/18
https://github.com/storageos/portal-manager/pull/24
=> Cleanup portal config

pkg/installer/install.go
I have a slow virtual machine, and hit the limit very often.
=> Increase timeout of wait for deployment ready

e2e/tests/dry-run/dry-run-test.sh, pkg/installer/install.go, pkg/version/version.go
I got permissions issue with the created directory, `0666` means anybody is able to read but noone is able to step into.
```
~mkdir asd
~chmod 0666 asd
~touch asd/asd
touch: cannot touch 'asd/asd': Permission denied
~chmod 0766 asd
~touch asd/asd
~
```
=> Fix dry run dir/file permissions

cmd/plugin/cli/upgrade.go, pkg/installer/installer.go
No real functionality changed, just adding the flags that are already available for uninstall and install.
=> Add flags to support upgrade in airgap cluster

pkg/installer/installer.go, pkg/installer/portal-manager.go, pkg/installer/uninstall.go, pkg/installer/upgrade.go
=> Add storageoscluster to object for uninstaller and portal-manager installer

api/v1/kubectlstorageosconfig_types.go, cmd/plugin/cli/install.go, e2e/tests/installer/stable/kubectl-storageos/00-install-full.yaml, e2e/tests/installer/stable/kubectl-storageos/02-assert.yaml, e2e/tests/installer/stable/kubectl-storageos/12-assert.yaml, pkg/installer/install.go, pkg/installer/installer.go
Allows users to specify the etcd pod's topology key during plugin install
=> allow setting topology key for etcd during install

Makefile, README.MD
bugfix release:
- unset --enable-metrics flag does not override cluster-config
=> release v1.3.1
